config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "tickets#index"

  resources :tickets do
    post :preview, on: :collection

    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_many :comments

  validates :title, :description, :reporter,
            presence: true

  validates :terms_of_service,
            presence: { if: :require_terms_of_service }

  attribute :terms_of_service, :boolean
  attribute :require_terms_of_service, :boolean
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = ticket.comments.create!(comment_params)

    redirect_to ticket
  end

  private

  def ticket
    Ticket.find(params[:ticket_id])
  end

  def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = Ticket.order(created_at: :desc)
  end

  def new
    @ticket = Ticket.new

    if params[:ticket]
      @ticket.assign_attributes(ticket_params)
    end
  end

  def preview
    @ticket = Ticket.new(ticket_params)

    render :new unless @ticket.valid?
  end

  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to @ticket,
                  notice: 'Ticket was successfully created.'
    else
      render :preview
    end
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  private

  def ticket_params
    params
      .require(:ticket)
      .permit(
        :title,
        :description,
        :reporter,
        :terms_of_service,
        :require_terms_of_service
      )
  end
  helper_method :ticket_params
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    Kramdown::Document.new(text).to_html.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConfirmationPageApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Montserrat', media: 'all' %>

    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div id="page">
      <h1><%= link_to "Random Support Board", :root %></h1>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tickets/index.html.erb
<p><%= link_to "New support ticket", [:new, :ticket] %></p>

<% @tickets.each do |ticket| %>
  <article>
    <h3>
      <%= link_to ticket.title, ticket %>
    </h3>
    <p>Reported by <strong><%= ticket.reporter %></strong>, <%= distance_of_time_in_words_to_now(ticket.created_at) %> ago</p>
  </article>
<% end %>

app/views/tickets/new.html.erb
<h3>New support ticket</h3>
<p><%= link_to "Go back", :root %></p>

<% if @ticket.errors.any? %>
  <ul class="errors">
    <% @ticket.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [:preview, @ticket] do |f| %>
  <p><%= f.text_field :title, placeholder: "Title" %></p>
  <p><%= f.text_area :description, placeholder: "Description" %></p>
  <p><%= f.text_field :reporter, placeholder: "Your name" %></p>

  <p><%= f.submit "Save" %></p>
<% end %>

app/views/tickets/preview.html.erb
<p>
  <%= link_to "Back", new_ticket_path(ticket: ticket_params)%>
</p>

<article>
  <h3>
    <%= @ticket.title %>
  </h3>
  <p>Reported by <strong><%= @ticket.reporter %></strong>, <%= distance_of_time_in_words_to_now(Time.now) %> ago</p>
  <div class="description"><%= markdown @ticket.description %></div>
</article>

<%= form_for @ticket do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :description %>
  <%= f.hidden_field :reporter %>
  <%= f.hidden_field :require_terms_of_service, value: 1 %>
  <p>
    <%= f.check_box :terms_of_service %>
    <%= f.label :terms_of_service, "I agree with the terms of service" %>
  </p>

  <p><%= f.submit "Create" %></p>
<% end %>

app/views/tickets/show.html.erb
<article>
  <h3>
    <%= @ticket.title %>
  </h3>
  <p>Reported by <strong><%= @ticket.reporter %></strong>, <%= distance_of_time_in_words_to_now(@ticket.created_at) %> ago</p>
  <div class="description"><%= markdown @ticket.description %></div>
</article>

<section id="comments">
  <% @ticket.comments.each do |comment| %>
    <article>
      <p><%= comment.name %> said:</p>
      <p><%= comment.body %></p>
    </article>
  <% end %>
</section>

<br />

<%= form_for [@ticket, Comment.new] do |f| %>
  <p><%= f.text_field :name, placeholder: "Your name" %></p>
  <p><%= f.text_area :body, placeholder: "Comment" %></p>
  <p><%= f.submit "Save" %></p>
<% end %>